version: '3.8'

services:
  frontend:
    build: '../'

    volumes:
      - ../:/tetris
      - /tetris/node_modules/

    command: serve tetris

    expose:
      - "3000"
    ports:
      - "3000:3000"
